/* ============================================================================
 *  PontusColor - OpenCL backend (Windows / Linux, AMD / Intel / NVIDIA)
 *  Builds the program from the embedded source once per OpenCL context and
 *  caches the kernel keyed by command queue (matches Resolve's usage model).
 * ==========================================================================*/

#include "PontusColorKernel.h"

#ifdef __APPLE__
#include <OpenCL/cl.h>
#else
#include <CL/cl.h>
#endif

#include <map>
#include <cstdio>
#include <mutex>

/* Embedded kernel source: PontusColorKernel.h + the OpenCL entry, generated by
 * CMake into PontusColorKernelSource.cpp */
extern const char* PontusColorKernelSource;

// -----------------------------------------------------------------------------
static void CheckError(cl_int p_Error, const char* p_Msg)
{
    if (p_Error != CL_SUCCESS)
        fprintf(stderr, "[PontusColor][OpenCL] %s  (error %d)\n", p_Msg, p_Error);
}

void RunOpenCLKernel(void* p_CmdQ, int p_Width, int p_Height,
                     const PCparams* p_Params, const float* p_Input, float* p_Output)
{
    cl_command_queue cmdQ = static_cast<cl_command_queue>(p_CmdQ);

    // Resolve gives device buffers as cl_mem already; the OFX host stores them
    // as void* that are valid cl_mem handles.
    cl_mem input  = reinterpret_cast<cl_mem>(const_cast<float*>(p_Input));
    cl_mem output = reinterpret_cast<cl_mem>(p_Output);

    static std::mutex sMutex;
    std::lock_guard<std::mutex> guard(sMutex);

    // cache kernels per command queue
    static std::map<cl_command_queue, cl_kernel> kernels;

    cl_kernel kernel = 0;
    std::map<cl_command_queue, cl_kernel>::iterator it = kernels.find(cmdQ);
    if (it == kernels.end())
    {
        cl_int err;
        cl_device_id deviceId = 0;
        err = clGetCommandQueueInfo(cmdQ, CL_QUEUE_DEVICE, sizeof(cl_device_id), &deviceId, 0);
        CheckError(err, "clGetCommandQueueInfo(device)");

        cl_context context = 0;
        err = clGetCommandQueueInfo(cmdQ, CL_QUEUE_CONTEXT, sizeof(cl_context), &context, 0);
        CheckError(err, "clGetCommandQueueInfo(context)");

        cl_program program = clCreateProgramWithSource(context, 1,
                                 (const char**)&PontusColorKernelSource, 0, &err);
        CheckError(err, "clCreateProgramWithSource");

        err = clBuildProgram(program, 1, &deviceId, "-cl-fast-relaxed-math", 0, 0);
        if (err != CL_SUCCESS)
        {
            char log[16384] = {0};
            clGetProgramBuildInfo(program, deviceId, CL_PROGRAM_BUILD_LOG,
                                  sizeof(log), log, 0);
            fprintf(stderr, "[PontusColor][OpenCL] build failed:\n%s\n", log);
        }

        kernel = clCreateKernel(program, "PontusColorKernelOpenCL", &err);
        CheckError(err, "clCreateKernel");

        kernels[cmdQ] = kernel;
    }
    else
    {
        kernel = it->second;
    }

    cl_int err = 0;
    int   ci   = 0;
    err  = clSetKernelArg(kernel, ci++, sizeof(int),      &p_Width);
    err |= clSetKernelArg(kernel, ci++, sizeof(int),      &p_Height);
    err |= clSetKernelArg(kernel, ci++, sizeof(PCparams), p_Params);
    err |= clSetKernelArg(kernel, ci++, sizeof(cl_mem),   &input);
    err |= clSetKernelArg(kernel, ci++, sizeof(cl_mem),   &output);
    CheckError(err, "clSetKernelArg");

    size_t localWorkSize[2]  = { 16, 16 };
    size_t globalWorkSize[2];
    globalWorkSize[0] = ((p_Width  + 15) / 16) * 16;
    globalWorkSize[1] = ((p_Height + 15) / 16) * 16;

    err = clEnqueueNDRangeKernel(cmdQ, kernel, 2, 0, globalWorkSize, localWorkSize, 0, 0, 0);
    CheckError(err, "clEnqueueNDRangeKernel");
}
