/* ============================================================================
 *  PontusColor - Metal backend (macOS, Apple Silicon + Intel)
 *  Compiles the embedded source once per device and caches the pipeline state
 *  keyed by command queue.
 * ==========================================================================*/

#import <Metal/Metal.h>

#include "PontusColorKernel.h"
#include <map>
#include <mutex>
#include <cstdio>

/* Embedded source: PontusColorKernel.h + the Metal entry, generated by CMake */
extern const char* PontusColorKernelSourceMetal;

void RunMetalKernel(void* p_CmdQ, int p_Width, int p_Height,
                    const PCparams* p_Params, const float* p_Input, float* p_Output)
{
    id<MTLCommandQueue> queue = reinterpret_cast<id<MTLCommandQueue> >(p_CmdQ);
    id<MTLDevice>       device = queue.device;

    static std::mutex sMutex;
    static std::map<id<MTLCommandQueue>, id<MTLComputePipelineState> > sPipelines;

    id<MTLComputePipelineState> pipeline = nil;
    {
        std::lock_guard<std::mutex> lock(sMutex);
        std::map<id<MTLCommandQueue>, id<MTLComputePipelineState> >::iterator it =
            sPipelines.find(queue);
        if (it == sPipelines.end())
        {
            NSError* err = nil;
            NSString* src = [NSString stringWithUTF8String:PontusColorKernelSourceMetal];
            MTLCompileOptions* opts = [MTLCompileOptions new];
            opts.fastMathEnabled = YES;
            id<MTLLibrary> lib = [device newLibraryWithSource:src options:opts error:&err];
            if (!lib)
            {
                fprintf(stderr, "[PontusColor][Metal] library compile failed: %s\n",
                        err ? [[err localizedDescription] UTF8String] : "unknown");
                return;
            }
            id<MTLFunction> fn = [lib newFunctionWithName:@"PontusColorKernelMetal"];
            pipeline = [device newComputePipelineStateWithFunction:fn error:&err];
            if (!pipeline)
            {
                fprintf(stderr, "[PontusColor][Metal] pipeline failed: %s\n",
                        err ? [[err localizedDescription] UTF8String] : "unknown");
                return;
            }
            sPipelines[queue] = pipeline;
        }
        else
        {
            pipeline = it->second;
        }
    }

    id<MTLBuffer> inBuf  = reinterpret_cast<id<MTLBuffer> >(const_cast<float*>(p_Input));
    id<MTLBuffer> outBuf = reinterpret_cast<id<MTLBuffer> >(p_Output);

    id<MTLCommandBuffer>        cmdBuf  = [queue commandBuffer];
    id<MTLComputeCommandEncoder> enc    = [cmdBuf computeCommandEncoder];
    [enc setComputePipelineState:pipeline];
    [enc setBytes:&p_Width  length:sizeof(int)      atIndex:0];
    [enc setBytes:&p_Height length:sizeof(int)      atIndex:1];
    [enc setBytes:p_Params  length:sizeof(PCparams) atIndex:2];
    [enc setBuffer:inBuf  offset:0 atIndex:3];
    [enc setBuffer:outBuf offset:0 atIndex:4];

    MTLSize tgSize = MTLSizeMake(16, 16, 1);
    MTLSize tgCount = MTLSizeMake((p_Width  + 15) / 16, (p_Height + 15) / 16, 1);
    [enc dispatchThreadgroups:tgCount threadsPerThreadgroup:tgSize];
    [enc endEncoding];
    [cmdBuf commit];
}
